# Generated by Django 3.0.3 on 2020-02-22 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('room', models.IntegerField()),
                ('sender', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('is_edited', models.BooleanField(verbose_name=False)),
                ('is_deleted', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField()),
                ('is_super', models.BooleanField(verbose_name=False)),
                ('is_ob', models.BooleanField(verbose_name=False)),
                ('is_expelled', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('timestamp', models.DateTimeField()),
                ('is_suspended', models.BooleanField(verbose_name=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.User')),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('is_lifted', models.BooleanField(verbose_name=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.User')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_limited', models.BooleanField(verbose_name=True)),
                ('is_revoked', models.BooleanField(verbose_name=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.Room')),
            ],
        ),
    ]
