"""
StringId enum container module.
Do not modify this file directly. It is generated from OB.strings.strings_generator.
"""


class StringId:
    """
    IDs used to get strings the string map (see OB.strings.strings_map).
    """

    Invalid = f"!@#$%^&*()"
    SystemUsername = f"OB-Sys"
    AnonPrefix = f"OB-Anon-"
    BanCaller = f"ban"
    BanCallerShort = f"b"
    BanManual = f"/{BanCaller} <user1> <user2> ... - Ban user(s) from your current room"
    ElevateCaller = f"elevate"
    ElevateCallerShort = f"e"
    ElevateManual = f"/{ElevateCaller} <command> <arg1> <arg2> ... <user> - Request an action be performed by a user with higher privilege"
    KickCaller = f"kick"
    KickCallerShort = f"k"
    KickManual = f"/{KickCaller} <user1> <user2> ... - Kick user(s) from your current room"
    LiftCaller = f"lift"
    LiftCallerShort = f"l"
    LiftManual = f"/{LiftCaller} <user1> <user2> ... - Lift ban on user(s) from your current room"
    ApplyCaller = f"apply"
    ApplyCallerShort = f"a"
    ApplyManual = f"/{ApplyCaller} <message> - Request to be hired as an Admin or promoted to Unlimited Admin"
    CreateCaller = f"create"
    CreateCallerShort = f"c"
    CreateManual = f"/{CreateCaller} - Create a new room"
    DeleteCaller = f"delete"
    DeleteCallerShort = f"d"
    DeleteManual = f"/{DeleteCaller} <room1> <room2> ... - Delete a room. Default: current room"
    FireCaller = f"fire"
    FireCallerShort = f"f"
    FireManual = f"/{FireCaller} <user1> <user2> ... - Reduces the privilege of an Admin or Unlimited Admin"
    HireCaller = f"hire"
    HireCallerShort = f"h"
    HireManual = f"/{HireCaller} <user1> <user2> ... - Make user(s) Admin of your current room"
    PrivateCaller = f"private"
    PrivateCallerShort = f"p"
    PrivateManual = f"/{PrivateCaller} /<user> <message> - Send a private message"
    WhoCaller = f"who"
    WhoCallerShort = f"w"
    WhoManual = f"/{WhoCaller} <room1> <room2> ... - See who is in a room. Default: current room"
    AnonBanning = f"You're not even logged in! Try making an account first, then we can talk about banning people."
    NonAdminBanning = (
        f"That's a little outside your pay-grade. Only admins may ban users. Try to /{ApplyCaller} to be an Admin."
    )
    BanSyntax = f"Usage: /{BanCaller} <user1> <user2> ..."
    UserNotPresent = f"Nobody named {0} in this room. Are you seeing things?"
    BanSelf = f"You can't ban yourself. Just leave the room. Or put yourself on time-out."
    TargetOwner = f"That's the owner. You know, your BOSS. Nice try."
    AlreadyBanned = f"That user is already banned. How unoriginal of you."
    Admin = f"Admin"
    JustLikeYou = f" just like you"
    Unlimited = f"Unlimited"
    BanPeer = f"{0} is an {1}, so you can't ban them. Feel free to /{ElevateCaller} your complaints to someone who has more authority."
    BanSenderReceiptPreface = f"Banned:"
    BanSenderReceiptNote = f"That'll show them."
    BanOccupantsNotificationPreface = f"One or more users have been banned:"
    BanOccupantsNotificationNote = f"Fear the almighty ban-hammer."
    AnonElevating = f"Why don't you make an account or log in first? Call us old-fashioned, but anons have very little privileges around these parts."
    NonAdminElevating = f"Elevation is a skill that only Admins are capable of wielding. You have yet to reach the level of Admin - come back when you're ready!"
    ElevateSyntax = f"Usage: /{ElevateCaller} (<command> <arg1> <arg2> ...) (<user1> <user2> ...) (<message>)"
    ElevateSelf = f"You can't elevate to yourself. Who do you think you are?"
    ElevatePeer = f"{0} does not have more privileges than you. What's the point of /{ElevateCaller} -ing to them?"
    ElevateSenderReceiptPreface = f"Sent an elevation request:"
    ElevateTargetsNotificationPreface = f"Received an elevation request from {0}"
    Recipients = f"Recipients:"
    CommandRequested = f"Command requested:"
    Message = f"Message:"
    AnonKicking = f"You're not even logged in! Try making an account first, then we can talk about kicking people."
    NonAdminKicking = (
        f"That's a little outside your pay-grade. Only admins may kick users. Try to /{ApplyCaller} to be an Admin."
    )
    KickSyntax = f"Usage: /{KickCaller} <user1> <user2> ..."
    KickSelf = f"You can't kick yourself. Just leave the room. Or put yourself on time-out."
    KickPeer = f"{0} is an {1}, so you can't kick them. Feel free to /{ElevateCaller} your complaints to someone who has more authority."
    KickSenderReceiptPreface = f"Kicked:"
    KickSenderReceiptNote = f"We'll see if they come back."
    KickOccupantsNotificationPreface = f"One or more users have been kicked:"
    KickOccupantsNotificationNote = f"Let this be a lesson to you all."
    AnonLifting = f"You are far from one who can lift bans. Log in and prove yourself an Admin."
    NonAdminLifting = f"A mere mortal like yourself does not have the power to lift bans. Try to /{ApplyCaller} to be an Admin and perhaps you may obtain this power if you are worthy."
    LiftSyntax = f"Usage: /{LiftCaller} <user1> <user2> ..."
    LiftInvalidTarget = (
        f"No user named {0} has been banned from this room. How can one lift that which has not been banned?"
    )
    LiftInsufficientPermission = f"{0} was banned by {1}. You cannot lift a ban issued by a user of equal or higher privilege than yourself. If you REALLY want to lift this ban you can /{ElevateCaller} to a higher authority."
    LiftSenderReceiptPreface = f"Ban lifted:"
    LiftSenderReceiptNote = f"Fully reformed and ready to integrate into society."
    AnonApplying = f"You can't get hired looking like that! Clean yourself up and make an account first."
    UnlimitedAdminApplying = f"You're already a big shot Unlimited Admin! There's nothing left to apply to."
    AdminSuffix = f" [Admin]"
    User = f"User:"
    Position = f"Position:"
    ApplySenderReceiptPreface = f"Application sent:"
    ApplySenderReceiptNote = f'Hopefully the response doesn\'t start with: "After careful consideration..."'
    ApplyTargetsNotificationPreface = f"Application Received:"
    ApplyTargetsNotificationNote = f"To hire this user, use /{HireCaller}."
    AnonCreating = f"Identify yourself! Must log in to create a room."
    CreateSyntax = f"Usage: /{CreateCaller} <name>"
    CreateSyntaxError = f"Room name cannot contain spaces."
    CreateExistingRoom = f"Someone beat you to it. {0} already exists."
    CreateSenderReceipt = f"Sold! Check out your new room: {0}"
    NonOwnerDeleting = f"Trying to delete someone else's room? How rude. Only the room owner may delete a room"
    DeleteSyntax = f"Usage: /{DeleteCaller} <room name> <owner username>"
    NonUnlimitedAdminFiring = f"That's a little outside your pay-grade. Only Unlimited Admins may fire admins. Try to /{ApplyCaller} to be Unlimited."
    FireSyntax = f"Usage: /{FireCaller} <user1> <user2> ..."
    FireUserNotPresent = f"{0} does not exist. You can't fire a ghost... can you?"
    FireSelf = f"You can't fire yourself. I don't care how bad your performance reviews are."
    FireNonAdmin = f"{0} is just a regular ol' user, so you can't fire them. You can /{1} or /{2} them if you want."
    FirePeer = f"{0} is an Unlimited Admin, so you can't fire them. Please direct all complaints to your local room owner, I'm sure they'll love some more paperwork to do..."
    FireSenderReceiptPreface = f"Fired:"
    FireSenderReceiptNote = f"It had to be done."
    FireOccupantsNotificationPreface = f"One or more users have been fired:"
    FireOccupantsNotificationNote = f"Those budget cuts are killer."
    FireTargetsNotificationNote = f"Clean out your desk."
    NonUnlimitedAdminHiring = f"That's a little outside your pay-grade. Only Unlimited Admins may hire admins. Try to /{ApplyCaller} to be Unlimited."
    HireSyntax = f"Usage: /{HireCaller} <user1> <user2> ..."
    HireInvalidTarget = f"{0} does not exist. Your imaginary friend needs an account before they can be an Admin."
    HireSelf = f"You can't hire yourself. I don't care how good your letter of recommendation is."
    HireAnon = f"{0} hasn't signed up yet. They cannot be trusted with the immense responsibility that is adminship."
    HireUnlimitedAdmin = f"{0} is already an Unlimited Admin. There's nothing left to /{1} them for."
    HireInsufficientPrivilege = f"{0} is already an Admin. Only the owner may promote them to Unlimited Admin"
    HireSenderReceiptPreface = f"Hired:"
    HireSenderReceiptNote = f"Now for the three-month evaluation period"
    HireOccupantsNotificationPreface = f"One or more users have been hired:"
    HireOccupantsNotificationNote = f"Drinks on them!"
    HireTargetsNotificationNote = f"With great power comes great responsibility."
    PrivateSyntax = f"Usage: /{PrivateCaller} /<user> <message>"
    PrivateInvalidSyntax = f'Looks like you forgot a "/" before the username. I\'ll let it slide.'
    PrivateInvalidTarget = f"{0} doesn't exist. Your private message will broadcasted into space instead."
    PrivateNoMessage = f"No message specified. Did you give up at just the username?"
    WhoInvalidTarget = f"{0} doesn't exist, so that probably means nobody is in there."
    WhoEmpty = f"{0} is all empty!"
    WhoPreface = f"Users in {0}:"
    OwnerSuffix = f" [Owner]"
    YouSuffix = f" [you]"
