# Generated by Django 3.0.3 on 2020-02-23 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_super", models.BooleanField(default=False)),
                ("is_ob", models.BooleanField(default=False)),
                ("is_expelled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_suspended", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_edited", models.BooleanField(verbose_name=False)),
                ("is_deleted", models.BooleanField(verbose_name=False)),
                (
                    "room",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.Room",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ban",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_lifted", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.Room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.User",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_limited", models.BooleanField(default=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.Room",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="OB.User",
                    ),
                ),
            ],
        ),
    ]
