# Generated by Django 3.0.3 on 2020-02-23 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("OB", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="room",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.Room"),
        ),
        migrations.AlterField(
            model_name="ban",
            name="room",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.Room"),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.Room"),
        ),
        migrations.CreateModel(
            name="OBUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_ob", models.BooleanField(default=False)),
                ("is_expelled", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.OBUser"),
        ),
        migrations.AlterField(
            model_name="ban",
            name="user",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.OBUser"),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.OBUser"),
        ),
        migrations.AlterField(
            model_name="room",
            name="owner",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="OB.OBUser"),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
