# Generated by Django 3.0.3 on 2020-03-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("OB", "0004_auto_20200314_1251"),
    ]

    operations = [
        migrations.RenameField(
            model_name="admin",
            old_name="user",
            new_name="ob_user",
        ),
        migrations.RenameField(
            model_name="ban",
            old_name="user",
            new_name="ob_user",
        ),
    ]
