# Generated by Django 3.0.3 on 2020-03-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OB", "0006_obuser_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="obuser",
            name="display_name",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
