# Generated by Django 3.0.3 on 2020-04-05 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OB', '0008_auto_20200324_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='occupants',
            field=models.ManyToManyField(related_name='occupied_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owned_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
