# Generated by Django 3.0.3 on 2020-04-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OB", "0010_auto_20200406_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="display_name",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
