# Generated by Django 3.0.3 on 2020-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OB", "0012_auto_20200424_0015"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="anonymous_username",
            new_name="anon_username",
        ),
        migrations.AddField(
            model_name="obuser",
            name="is_anon",
            field=models.BooleanField(default=False),
        ),
    ]
