# Generated by Django 3.0.3 on 2020-04-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OB', '0013_auto_20200424_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obuser',
            name='display_name',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
