# Generated by Django 3.0.3 on 2020-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OB', '0014_auto_20200424_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obuser',
            name='display_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
