# Generated by Django 3.0.3 on 2020-05-03 05:39

import OB.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("OB", "0015_auto_20200426_1943"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="group_type",
            field=models.SmallIntegerField(default=OB.constants.GroupTypes["Room"]),
        ),
    ]
