# Generated by Django 3.0.3 on 2020-05-22 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OB', '0020_auto_20200511_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='OB.Room'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ban',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='OB.Room'),
        ),
        migrations.AlterField(
            model_name='ban',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='OB.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
