# Generated by Django 3.0.6 on 2020-07-14 03:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OB', '0025_auto_20200713_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='exclusions',
            field=models.ManyToManyField(default=None, related_name='message_excluded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(default=None, related_name='message_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
